/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as PublicIndexRouteImport } from './pages/_public/index'
import { Route as PrivateClientesIndexRouteImport } from './pages/_private/clientes/index'
import { Route as PrivateClientesSelecionadosIndexRouteImport } from './pages/_private/clientes/selecionados/index'
import { Route as PrivateClientesDetalhesIndexRouteImport } from './pages/_private/clientes/detalhes/index'

const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/_public/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateClientesIndexRoute = PrivateClientesIndexRouteImport.update({
  id: '/_private/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateClientesSelecionadosIndexRoute =
  PrivateClientesSelecionadosIndexRouteImport.update({
    id: '/_private/clientes/selecionados/',
    path: '/clientes/selecionados/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivateClientesDetalhesIndexRoute =
  PrivateClientesDetalhesIndexRouteImport.update({
    id: '/_private/clientes/detalhes/',
    path: '/clientes/detalhes/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/clientes': typeof PrivateClientesIndexRoute
  '/clientes/detalhes': typeof PrivateClientesDetalhesIndexRoute
  '/clientes/selecionados': typeof PrivateClientesSelecionadosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/clientes': typeof PrivateClientesIndexRoute
  '/clientes/detalhes': typeof PrivateClientesDetalhesIndexRoute
  '/clientes/selecionados': typeof PrivateClientesSelecionadosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public/': typeof PublicIndexRoute
  '/_private/clientes/': typeof PrivateClientesIndexRoute
  '/_private/clientes/detalhes/': typeof PrivateClientesDetalhesIndexRoute
  '/_private/clientes/selecionados/': typeof PrivateClientesSelecionadosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clientes' | '/clientes/detalhes' | '/clientes/selecionados'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clientes' | '/clientes/detalhes' | '/clientes/selecionados'
  id:
    | '__root__'
    | '/_public/'
    | '/_private/clientes/'
    | '/_private/clientes/detalhes/'
    | '/_private/clientes/selecionados/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PrivateClientesIndexRoute: typeof PrivateClientesIndexRoute
  PrivateClientesDetalhesIndexRoute: typeof PrivateClientesDetalhesIndexRoute
  PrivateClientesSelecionadosIndexRoute: typeof PrivateClientesSelecionadosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/clientes/': {
      id: '/_private/clientes/'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof PrivateClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/clientes/selecionados/': {
      id: '/_private/clientes/selecionados/'
      path: '/clientes/selecionados'
      fullPath: '/clientes/selecionados'
      preLoaderRoute: typeof PrivateClientesSelecionadosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/clientes/detalhes/': {
      id: '/_private/clientes/detalhes/'
      path: '/clientes/detalhes'
      fullPath: '/clientes/detalhes'
      preLoaderRoute: typeof PrivateClientesDetalhesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PrivateClientesIndexRoute: PrivateClientesIndexRoute,
  PrivateClientesDetalhesIndexRoute: PrivateClientesDetalhesIndexRoute,
  PrivateClientesSelecionadosIndexRoute: PrivateClientesSelecionadosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
